spring:
  application:
    name: DevVault


  #database
  data:
    mongodb:
      uri: mongodb://localhost:27017/dev_vault
      username: root
      password: root


  #mail properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD}
    protocol: smtp
    properties.mail.smtp:
      tls: true
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com



#custom variables
account:
  verification:
    auth:
      url: "http://localhost:8080/api/auth/accountVerification/"
token:
  prefix: "Bearer "